owner: coinsambacom
repo: upptime
user-agent: upptime
sites:
  - name: Coinsamba
    url: https://coinsamba.com
  - name: Coinsamba P2P
    url: https://p2p.coinsamba.com
  - name: Coinsamba API
    url: https://api.coinsamba.com
status-website:
  cname: status.coinsamba.com
  logoUrl: https://f6s-public.s3.amazonaws.com/profiles/2627844_original.jpg
  name: Coinsamba Status
  introTitle: "Coinsamba"
  introMessage: We work hard to make sure Coinsamba is always online and ready to help you! If you are experiencing issues, please reference the chart below.
